### PR TITLE
HasDynamicArrays function

### PR DESCRIPTION
**Pull request by malankriel**
Not sure how to test this? I can see it returns true on my machine, as it should.

### CODE REVIEW

**Comment by rudolfbyker** [comment]
The only way to test this is:

1. Detect the Excel version in the unit test, and run a different assertion based on that.
2. Run the test on multiple Excel versions (e.g. multiple VMs with different Excel versions).

**Comment by rudolfbyker** [comment]
The code looks fine. Using `static` here is clever.

**Comment by malankriel** [comment]
> The only way to test this is:
> 
> 1. Detect the Excel version in the unit test, and run a different assertion based on that.
> 2. Run the test on multiple Excel versions (e.g. multiple VMs with different Excel versions).

But for (1), we use this function to detect the Excel version :)

**Comment by rudolfbyker** [comment]
No, I'm talking about a unit test written in Python, which will have to detect it in some other way.

**Pull request merged**
